baseurl = "http://gogo.tattoo/aid/"
languageCode = "en-us"
title = "Valentin Aidov @ gogo.tattoo"
copyright = "Valentin Aidov"
googleAnalytics = "UA-79234406-1"

defaultContentLanguage = "en"

[Languages]
  [Languages.en]
    weight = 1
    title = "Valentin Aidov @ gogo.tattoo"
  [Languages.zh]
    weight = 3
    title = "Valentin Aidov @ gogo.tattoo"
  [Languages.zh-hant]
    weight = 2
    title = "Valentin Aidov @ gogo.tattoo"
  [Languages.ru]
    weight = 2
    title = "Valentin Aidov @ gogo.tattoo"

[params]
# The path must be relative to the static folder
favicon = "favicon.ico"

[params.profile]
  name = "Valentin Aidov"
  avatar = "images/aid.png"
  description = "profile.description"
  experience = "profile.experience"
  location = "profile.location"
  origin = "profile.origin"

# Navigation
[params.navigation]
  brand = "aid @ gogo tattoo  (Alpha)"

  [params.navigation.links]
    about     = "nav.about"
    services  = "nav.services"
    portfolio = "nav.portfolio"
    contact   = "nav.contact"
