baseurl = "http://gogo.tattoo/aid/"
languageCode = "en-us"
title = "Valentin Aidov @ gogo.tattoo"
copyright = "Valentin Aidov"
googleAnalytics = "UA-79234406-1"

[params]
# The path must be relative to the static folder
favicon = "favicon.ico"

[params.profile]
  name = "Valentin Aidov"
  avatar = "images/aid.png"
  description = "profile.description"
  experience = "10+ years (since 2006)"
  location = "Gatchina"
  origin = "Russia"

# Navigation
[params.navigation]
  brand = "aid @ gogo tattoo  (Alpha)"

  [params.navigation.links]
    about     = "nav.about"
    services  = "nav.services"
    portfolio = "nav.portfolio"
    contact   = "nav.contact"
