baseurl = "http://gogo.tattoo/aid/"
languageCode = "en-us"
title = "Valentin Aidov @ gogo.tattoo"
copyright = "Valentin Aidov"
googleAnalytics = "UA-79234406-1"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = "false"

[Languages]
  [Languages.en]
    weight = 1
  [Languages.zh]
    weight = 3
  [Languages.zh-hant]
    weight = 2
  [Languages.ru]
    weight = 2

[params]
# The path must be relative to the static folder
favicon = "favicon.ico"

[params.profile]
  name = "Valentin Aidov"
  fullname = "profile.fullname"
  avatar = "/images/aid.png"
  description = "profile.description"
  experience = "profile.experience"
  location = "profile.location"
  origin = "profile.origin"

# Navigation
[params.nav]
  tattoo = "nav.tattoo"
  henna = "nav.henna"
  design = "nav.design"
  piercing = "nav.piercing"
  dreadlocks = "nav.dreadlocks"
  contact = "nav.contact"

[params.navigation]
  brand = "aid @ gogo tattoo  (Alpha)"

  [params.navigation.links]
    about     = "nav.about"
    services  = "nav.services"
    portfolio = "nav.portfolio"
    contact   = "nav.contact"
